### ISSUE TITLE
Can't use Alt Gr for special letters on German Keyboard

### ISSUE THREAD

**Issue by RegenJacob** [ishland/fix-keyboard-on-linux#2]
On some keyboards like the German keyboard there is the `Alt Gr` key.
It's for some symbols like @,€ and is quite important.

It could be that `Screen.hasAltDown()` also triggers when `Alt Gr` is down or maybe it's something else but currently it doesn't work

**Comment by SzczurekYT** [comment]
Probably the same issue, with the mod I can't type polish letters like ą, ć, ę, ł, ś, ż, ź with the right alt key. This is a pretty big deal since you can't use proper grammar with the mod.

**Comment by ishland** [comment]
I'm not quite sure how to deal with this situation but in 3d32d3cdf04737204fc5f14c057701fb58777ee0 it now only checks left alt key. Please check if this solves the issue.

**Comment by RegenJacob** [comment]
Works for me I assume it works for @SzczurekYT too

**Comment by SzczurekYT** [comment]
Works for me too, thank you. Finally I can have full keyboard experience on wayland linux.
