### ISSUE TITLE
Fix "t" character when opening chat

### ISSUE THREAD

**Issue by Hyphonical** [ishland/fix-keyboard-on-linux#4]
Please add a fix to stop the "t" character from appearing in chat when opening chat

**Comment by Farmer-Markus** [comment]
yes please :D its so annoying

**Comment by ArduFish** [comment]
https://bugs.mojang.com/browse/MC-122477 contains a code analysis. Also affects /

**Comment by Farmer-Markus** [comment]
For everyone keep searching for a solution of this problem [this](https://github.com/RecursiveG/Mc122477Fix) guys found a solution but not for the latest fabric versions. I've forked the mod and released for newer versions [here](https://github.com/Farmer-Markus/Mc122477Fix/releases). Have fun :)

**Comment by Hyphonical** [comment]
I suppose this qualifies as a fix. Thanks
